apiVersion: v1
kind: ConfigMap
metadata:
  name: documentserver
data:
  DB_USER: postgres
  DB_HOST: postgresql
  DB_PORT: "5432"
  REDIST_SERVER_HOST: redis-master
  AMQP_HOST: rabbitmq-ha
  AMQP_USER: user
  AMQP_PROTO: amqp
  METRICS_HOST: statsd
  METRICS_ENABLED: "false"
  SPELLCHECKER_HOST_PORT: spellchecker:8080
  EXAMPLE_HOST_PORT: example:8080
