{{- if .Values.example.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
data:
  DS_URL: {{ .Values.example.dsUrl }}
{{- end }}
